import argparse
import os

import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import MinMaxScaler

import preprocess

WEIGHTS_FILE = "inference_weights.c"


def create_model(max_iter=500):
    """Define the sklearn MLP model for motor control."""
    return MLPRegressor(
        hidden_layer_sizes=(64, 32),
        activation='relu',
        solver='adam',
        max_iter=max_iter,
        random_state=42,
    )


def generate_dummy_data(samples=1000):
    """Generate synthetic data for pipeline testing."""
    print("Generating dummy data...")
    rng = np.random.default_rng(42)
    # Features: target_l, actual_l, target_r, actual_r, gyro_z
    x = rng.uniform(low=0.0, high=1.0, size=(samples, 5))
    # Targets: pwm_l, pwm_r in nanoseconds
    y = rng.uniform(low=1000000.0, high=2000000.0, size=(samples, 2))
    return x, y


def _write_c_float_array(file_obj, name, values):
    values_fmt = ", ".join([f"{float(v):.6f}f" for v in values])
    file_obj.write(f"const float {name}[{len(values)}] = {{{values_fmt}}};\n")


def export_weights_to_c(model, output_path, scalers):
    """Export model weights and fitted scaler bounds to C."""
    scaler_x, scaler_y = scalers
    feature_min = scaler_x.data_min_
    feature_max = scaler_x.data_max_
    target_min = scaler_y.data_min_
    target_max = scaler_y.data_max_

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by train.py */\n")
        f.write("#include \"../include/inference.h\"\n\n")

        f.write("// Fitted scaler bounds from training data\n")
        _write_c_float_array(f, "FEATURE_MIN", feature_min)
        _write_c_float_array(f, "FEATURE_MAX", feature_max)
        _write_c_float_array(f, "TARGET_MIN", target_min)
        _write_c_float_array(f, "TARGET_MAX", target_max)
        f.write("\n")

        # Layer 1 (Input -> Hidden 1)
        w1 = model.coefs_[0]
        b1 = model.intercepts_[0]

        f.write(f"// Layer 1: {w1.shape[0]} inputs -> {w1.shape[1]} neurons\n")
        f.write(f"const float LAYER_1_WEIGHTS[{w1.shape[0]}][{w1.shape[1]}] = {{\n")
        for i in range(w1.shape[0]):
            f.write("    {")
            f.write(", ".join([f"{x:.6f}f" for x in w1[i]]))
            f.write("},\n")
        f.write("};\n\n")

        f.write(f"const float LAYER_1_BIAS[{b1.shape[0]}] = {{\n")
        f.write("    " + ", ".join([f"{x:.6f}f" for x in b1]) + "\n")
        f.write("};\n\n")

        # Layer 2 (Hidden 1 -> Hidden 2)
        w2 = model.coefs_[1]
        b2 = model.intercepts_[1]

        f.write(f"// Layer 2: {w2.shape[0]} inputs -> {w2.shape[1]} neurons\n")
        f.write(f"const float LAYER_2_WEIGHTS[{w2.shape[0]}][{w2.shape[1]}] = {{\n")
        for i in range(w2.shape[0]):
            f.write("    {")
            f.write(", ".join([f"{x:.6f}f" for x in w2[i]]))
            f.write("},\n")
        f.write("};\n\n")

        f.write(f"const float LAYER_2_BIAS[{b2.shape[0]}] = {{\n")
        f.write("    " + ", ".join([f"{x:.6f}f" for x in b2]) + "\n")
        f.write("};\n\n")

        # Layer 3 (Hidden 2 -> Output)
        w3 = model.coefs_[2]
        b3 = model.intercepts_[2]

        f.write(f"// Layer 3: {w3.shape[0]} inputs -> {w3.shape[1]} outputs\n")
        f.write(f"const float LAYER_3_WEIGHTS[{w3.shape[0]}][{w3.shape[1]}] = {{\n")
        for i in range(w3.shape[0]):
            f.write("    {")
            f.write(", ".join([f"{x:.6f}f" for x in w3[i]]))
            f.write("},\n")
        f.write("};\n\n")

        f.write(f"const float LAYER_3_BIAS[{b3.shape[0]}] = {{\n")
        f.write("    " + ", ".join([f"{x:.6f}f" for x in b3]) + "\n")
        f.write("};\n\n")

    print(f"Exported weights + scalers to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Train Motor Control ML Model")
    parser.add_argument("--dummy-data", action="store_true", help="Use dummy data for testing")
    parser.add_argument("--max-iter", type=int, default=500, help="Max MLP training iterations")
    parser.add_argument("--log-dir", type=str, default="", help="Optional path to CSV logs directory")
    parser.add_argument("--no-plot", action="store_true", help="Disable plotting training results")
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    default_log_dir = os.path.join(project_root, "logs")
    output_path = os.path.join(project_root, "c_code", "src", WEIGHTS_FILE)

    x, y, scalers = None, None, None

    if args.dummy_data:
        x_raw, y_raw = generate_dummy_data()
        scaler_x = MinMaxScaler()
        scaler_y = MinMaxScaler()
        x = scaler_x.fit_transform(x_raw)
        y = scaler_y.fit_transform(y_raw)
        scalers = (scaler_x, scaler_y)
    else:
        log_dir = args.log_dir.strip() if args.log_dir else default_log_dir
        if not os.path.isabs(log_dir):
            log_dir = os.path.abspath(os.path.join(os.getcwd(), log_dir))

        if not os.path.exists(log_dir):
            print(f"Error: Log directory {log_dir} not found.")
            return

        print(f"Loading data from {log_dir}...")
        df = preprocess.load_data(log_dir)
        if df is None:
            print("No data loaded. Use --dummy-data to test pipeline.")
            return

        x, y, scalers = preprocess.preprocess_data(df)
        if x is None:
            print("Preprocessing failed.")
            return

    print(f"Training on {len(x)} samples...")

    model = create_model(max_iter=args.max_iter)
    model.fit(x, y)

    print("Training complete. Exporting weights to C...")
    export_weights_to_c(model, output_path, scalers)

    if not args.no_plot:
        try:
            import matplotlib.pyplot as plt
            print("Generating plots (close windows to exit)...")
            
            plt.figure(figsize=(12, 5))
            
            # Plot Loss Curve
            plt.subplot(1, 2, 1)
            plt.plot(model.loss_curve_, label="Training Loss")
            plt.title("MLP Training Loss")
            plt.xlabel("Iterations")
            plt.ylabel("MSE Loss")
            plt.legend()
            plt.grid(True)
            
            # Plot Predictions vs Actual (Scatter plot)
            plt.subplot(1, 2, 2)
            y_pred = model.predict(x)
            
            # Inverse transform to show actual PWM ns
            scaler_y = scalers[1]
            y_actual_real = scaler_y.inverse_transform(y)
            y_pred_real = scaler_y.inverse_transform(y_pred)
            
            # Sample data to avoid over-cluttering if datasets are huge
            n_samples = min(len(y), 2000)
            indices = np.random.choice(len(y), n_samples, replace=False)
            
            plt.scatter(y_actual_real[indices, 0], y_pred_real[indices, 0], alpha=0.3, label="PWM Left", marker='o')
            plt.scatter(y_actual_real[indices, 1], y_pred_real[indices, 1], alpha=0.3, label="PWM Right", marker='x')
            
            min_val = min(y_actual_real.min(), y_pred_real.min())
            max_val = max(y_actual_real.max(), y_pred_real.max())
            plt.plot([min_val, max_val], [min_val, max_val], 'r--', label="Perfect Prediction")
            
            plt.title("Predicted vs Actual (Sampled)")
            plt.xlabel("Actual PWM (ns)")
            plt.ylabel("Predicted PWM (ns)")
            plt.legend()
            plt.grid(True)
            
            plt.tight_layout()
            plt.show()
        except ImportError:
            print("matplotlib is not installed. Plots disabled.")


if __name__ == "__main__":
    main()
