import argparse
import os

import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import MinMaxScaler

import preprocess

WEIGHTS_FILE = "inference_weights.c"


def create_model(max_iter=500):
    """Define the sklearn MLP model for motor control."""
    return MLPRegressor(
        hidden_layer_sizes=(64, 32),
        activation='relu',
        solver='adam',
        max_iter=max_iter,
        random_state=42,
    )

def _write_c_float_array(file_obj, name, values):
    values_fmt = ", ".join([f"{float(v):.6f}f" for v in values])
    file_obj.write(f"const float {name}[{len(values)}] = {{{values_fmt}}};\n")


def export_weights_to_c(model, output_path, scalers):
    """Export model weights and fitted scaler bounds to C."""
    scaler_x, scaler_y = scalers
    feature_min = scaler_x.data_min_
    feature_max = scaler_x.data_max_
    target_min = scaler_y.data_min_
    target_max = scaler_y.data_max_

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by train.py */\n")
        f.write("#include \"../include/inference.h\"\n\n")

        f.write("// Fitted scaler bounds from training data\n")
        _write_c_float_array(f, "FEATURE_MIN", feature_min)
        _write_c_float_array(f, "FEATURE_MAX", feature_max)
        _write_c_float_array(f, "TARGET_MIN", target_min)
        _write_c_float_array(f, "TARGET_MAX", target_max)
        f.write("\n")

        # Layer 1 (Input -> Hidden 1)
        w1 = model.coefs_[0]
        b1 = model.intercepts_[0]

        f.write(f"// Layer 1: {w1.shape[0]} inputs -> {w1.shape[1]} neurons\n")
        f.write(f"const float LAYER_1_WEIGHTS[{w1.shape[0]}][{w1.shape[1]}] = {{\n")
        for i in range(w1.shape[0]):
            f.write("    {")
            f.write(", ".join([f"{x:.6f}f" for x in w1[i]]))
            f.write("},\n")
        f.write("};\n\n")

        f.write(f"const float LAYER_1_BIAS[{b1.shape[0]}] = {{\n")
        f.write("    " + ", ".join([f"{x:.6f}f" for x in b1]) + "\n")
        f.write("};\n\n")

        # Layer 2 (Hidden 1 -> Hidden 2)
        w2 = model.coefs_[1]
        b2 = model.intercepts_[1]

        f.write(f"// Layer 2: {w2.shape[0]} inputs -> {w2.shape[1]} neurons\n")
        f.write(f"const float LAYER_2_WEIGHTS[{w2.shape[0]}][{w2.shape[1]}] = {{\n")
        for i in range(w2.shape[0]):
            f.write("    {")
            f.write(", ".join([f"{x:.6f}f" for x in w2[i]]))
            f.write("},\n")
        f.write("};\n\n")

        f.write(f"const float LAYER_2_BIAS[{b2.shape[0]}] = {{\n")
        f.write("    " + ", ".join([f"{x:.6f}f" for x in b2]) + "\n")
        f.write("};\n\n")

        # Layer 3 (Hidden 2 -> Output)
        w3 = model.coefs_[2]
        b3 = model.intercepts_[2]

        f.write(f"// Layer 3: {w3.shape[0]} inputs -> {w3.shape[1]} outputs\n")
        f.write(f"const float LAYER_3_WEIGHTS[{w3.shape[0]}][{w3.shape[1]}] = {{\n")
        for i in range(w3.shape[0]):
            f.write("    {")
            f.write(", ".join([f"{x:.6f}f" for x in w3[i]]))
            f.write("},\n")
        f.write("};\n\n")

        f.write(f"const float LAYER_3_BIAS[{b3.shape[0]}] = {{\n")
        f.write("    " + ", ".join([f"{x:.6f}f" for x in b3]) + "\n")
        f.write("};\n\n")

    print(f"Exported weights + scalers to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Train Motor Control ML Model")
    parser.add_argument("--max-iter", type=int, default=500, help="Max MLP training iterations")
    parser.add_argument("--log-dir", type=str, default="", help="Optional path to CSV logs directory")
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    default_log_dir = os.path.join(project_root, "logs")
    output_path = os.path.join(project_root, "c_code", "src", WEIGHTS_FILE)

    log_dir = args.log_dir.strip() if args.log_dir else default_log_dir
    if not os.path.isabs(log_dir):
        log_dir = os.path.abspath(os.path.join(os.getcwd(), log_dir))

    if not os.path.exists(log_dir):
        print(f"Error: Log directory {log_dir} not found.")
        return

    print(f"Loading data from {log_dir}...")
    df = preprocess.load_data(log_dir)
    if df is None:
        print("No data loaded. Cannot train model.")
        return

    x, y, scalers = preprocess.preprocess_data(df)
    if x is None:
        print("Preprocessing failed.")
        return

    print(f"Training on {len(x)} samples...")

    model = create_model(max_iter=args.max_iter)
    model.fit(x, y)

    print("Training complete. Exporting weights to C...")
    export_weights_to_c(model, output_path, scalers)


if __name__ == "__main__":
    main()
